name: Ruby Gem Build and Publish

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
    types:
      - closed

jobs:
  test:
    uses: ./.github/workflows/lint_test.yml
  
  build:
    if: github.event.pull_request.merged || github.event_name == 'workflow_dispatch'
    name: Build and Publish
    needs: [test]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby 3.2
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2

    - name: Publish to RubyGems
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push *.gem
      env:
        GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
